# !/bin/bash
# PBS -l nodes=1:ppn=1
# PBS -N test 
cd $PBS_O_WORKDIR
export NPROCS=`wc -l $PBS_NODEFILE |gawk '//{print $1}'`
export PATH="/home/users/hahn/anaconda2/bin:$PATH"

export CENTRALMS_DIR="/mount/sirocco1/hahn/centralms/"
export CENTRALMS_CODEDIR="/home/users/hahn/projects/centralMS/"

/home/users/hahn/anaconda2/bin/python /home/users/hahn/projects/centralMS/run/abc.py noabias 5 2 10 

